### ISSUE TITLE
link not working 

### ISSUE THREAD

**Issue by ghost** [melvincwng/facebook-clone#1]
live demo link not working

**Comment by ghost** [comment]
@melvincwng 
![Screenshot_20220811_102558](https://user-images.githubusercontent.com/110934920/184067122-e5de4462-fb4e-4978-b951-87b938764b79.jpg)

**Comment by melvincwng** [comment]
Hi @vinothkumar-ERROR, please take note of the following (copy pasted from the README.md)

> Please also take note when visiting the website, Google Search Console may mistakenly flag a warning page on your screen due to it's high resemblance with the actual Facebook login page.

> To get to the actual website from the warning page, simply click 'Details' > 'Visit this unsafe site'.

> Please be assured that this is a safe website - it's a pure frontend webpage that I've included as one of my portfolio projects. That's it - no server/database backend logic, entirely frontend code only ^^.

**Comment by melvincwng** [comment]
Unfortunately @vinothkumar-ERROR, Google Search Console occasionally flags that website incorrectly.

To access the link, try in another browser that allows you to click these options 'Details' > 'Visit this unsafe site'.

Please be informed this website is safe, and it is simply just a portfolio project.

**Comment by ghost** [comment]
you can host this repo in GitHub pages

**Comment by melvincwng** [comment]
@vinothkumar-ERROR , it will eventually get flagged incorrectly by Google Search Console regardless of hosting in GitHub Pages or Netlify.

Hope this clarifies.
